name: Deploy SvelteKit App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOMAIN: 'pleasefix.me'
  NODE_VERSION: '21.7.1'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Prepare Build for Deployment
        run: |
          cp package.json ./build/
          cp yarn.lock ./build/
          mkdir ./build/prisma
          cp prisma/schema.prisma ./build/prisma/
          cp -r prisma/migrations ./build/prisma/
          tar -czvf build.tar.gz -C ./build .

      - name: Generate Timestamp
        id: get_timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

      - name: Copy Build to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'build.tar.gz'
          target: '/var/www/${{env.DOMAIN}}/${{ steps.get_timestamp.outputs.timestamp }}'

      - name: Unpack Build on Server and Reload App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Unpack build
            cd /var/www/${{env.DOMAIN}}/${{ steps.get_timestamp.outputs.timestamp }}
            tar -xvzf build.tar.gz

            # Prepare for production
            yarn install --production

            # Install prisma cli and add it to path temporarily
            yarn add -D prisma
            export PATH=$PATH:$(pwd)/node_modules/.bin


            # Link current to new build
            ln -sfn /var/www/${{env.DOMAIN}}/${{ steps.get_timestamp.outputs.timestamp }} /var/www/${{env.DOMAIN}}/current

            # Generate a temporary .env file for PM2 to use
            echo "GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}" > .env
            echo "SESSION_ENCRYPTION_KEY=${{ secrets.SESSION_ENCRYPTION_KEY }}" >> .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

            # Update Prisma Schema
            prisma generate
            prisma migrate deploy

            # Reload PM2 process with new environment variables
            env $(cat .env | grep -v "^#" | xargs) sh -c 'pm2 reload ../ecosystem.config.js --env production --update-env'

            # Cleanup temporary .env file
            # rm .env

      - name: Execute Cleanup Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/${{env.DOMAIN}}
            ./cleanup.sh
